# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dc7677407a6d022f02a22a992c6d26c5701187475b2f919b9e7c0ac4725bfcfab80fbaa54cad736a0360b68c9155617552a8ca704ff61e4f155e3a301d83e07

test:
  secret_key_base: 70ba3ad877a6122cd9e483ab323e7be64d4c0d09456bacb81a8c83f0949b9193f890f94f7dec46f074b8636cd8967d45fdd27a489147f625c2d03901d281e5df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
